{% set version = "0.20.0" %}

package:
  name: pyjanitor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyjanitor/pyjanitor-{{ version }}.tar.gz
  sha256: 1f9d817c75db4d22f1ffe7cda7904d39c2bf1d8e0ea8abecac4054911315ffa4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - scikit-learn
    - pandas-flavor

test:
  imports:
    - janitor

about:
  home: https://github.com/ericmjl/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python implementation of the R package janitor.'
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/ericmjl/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
