{% set version = "0.20.13" %}

package:
  name: pyjanitor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyjanitor/pyjanitor-{{ version }}.tar.gz
  sha256: b14969927279a4b98dac8b659454018a55a145a17fda804f0ed288aaa0ad4c85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - multipledispatch
    - natsort
    - numpy
    - pandas
    - pandas-flavor
    - requests
    - scikit-learn
    - scipy
    - xarray
    - xlrd

test:
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - janitor

about:
  home: https://github.com/ericmjl/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/ericmjl/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
