{% set version = "0.12.0" %}

package:
  name: pyjanitor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyjanitor/pyjanitor-{{ version }}.tar.gz
  sha256: 5f06a97027cbd4305cb975502da1ac552550948e8d218f35d014637d5cdc9ba0

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - scikit-learn
    - pandas-flavor

test:
  imports:
    - janitor

about:
  home: https://github.com/ericmjl/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python implementation of the R package janitor.'
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/ericmjl/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
