{% set name = "pyjanitor" %}
{% set version = "0.1.2" %}
{% set sha256 = "f32297e8a412dee0edf4397182443fdbb96139466fd055c0f6f904a61ab98a8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [py<36]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - numpy
    - scikit-learn

test:
  imports:
    - janitor

about:
  home: https://github.com/ericmjl/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python implementation of the R package janitor.'
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/ericmjl/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
