{% set version = "0.20.4" %}

package:
  name: pyjanitor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyjanitor/pyjanitor-{{ version }}.tar.gz
  sha256: 34718347b48590bb8176cc897a0d7905105c6d70ce4859aa78382288efbb93d9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - scikit-learn
    - pandas-flavor
    - natsort

test:
  imports:
    - janitor

about:
  home: https://github.com/ericmjl/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python implementation of the R package janitor.'
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/ericmjl/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
