{% set version = "0.20.8" %}

package:
  name: pyjanitor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyjanitor/pyjanitor-{{ version }}.tar.gz
  sha256: 6314e2375c8fb0ebeb72a8479ef2da6d850cb95c251d13b98ddc3d14dcd86572

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - scikit-learn
    - pandas-flavor
    - natsort
    - requests
    - xlrd

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - janitor

about:
  home: https://github.com/ericmjl/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python implementation of the R package janitor.
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/ericmjl/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
