travis:
  secure:
    BINSTAR_TOKEN: YWfEgD1qa4MNsA+1qZVaOq+BcDfhQ9ro+Lx/nrHxkdvld2EnSsE2clioGKOd88L1ndIocYafiV3ZofnoiT4PB8TaZ2RZivfSe0MlOgjXSaV0qZaAQQKYdlwiUOLLdIREnvovoQC1vU8eWie6KMUJAYSUkjk6UwvxTx+Re8DT9jKy+qs5UhB9MagJEgWBdY/jWbD/t0Fiz/ri27qglZl8JlrwahSq6/3Gu3MTLkPuU93/4ir3zeDnEUJZ6Fu5dvg0auOhZKTwJbe0vifJBHJN1zqSC5SXX8TkHXqbfRKs1aTMLHQfIiecwX7QqcAI+bmcJI3WXT9bE/HmTMjy3m+q//X3I1/C5BqNux+osnPwP+ThJ7Uuq+HNLBh55IXwI3bNKl0AxOn/a3/+NlOxScF40UJb/H662ybfVWFJAAF+gBAbRhan9F0LLMgP0Zr4y09VSb7ecHhQdGFPc++iiDLLK/5gqMSux73Fl/KXxlrG0v4/CpLyeymIuMnpuLFimoJeCBIdzmQrqWC/Mq4xIILS+ZMwBFk4+3ldQPuyOV5i7+VqG11WbMxcbB2sAzN/BgOLYtItiwx8E6Ok9S3wbPAHXo5R0swRIccaHvs9vX0w3zL0fzRt5fdR8VAToKR27lrk6ZG03yywMu/p3I8x3k40jQTGMSKixh9a2OHDArkBG/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
