travis:
  secure:
    BINSTAR_TOKEN: R+BbWJw02rKdwOGO4ojqXgZ6j3uRVxRRXw0V/EPnrjgLiYIeShaQcsdtQCrLeBd4SxyHIZJLOWpD4vCiNL/9+Zyokn35hXfkytXyO8n64PBbs0SMRLHaXEjdmQxVYkSefzOv9deA2l6u1zKqEwoH19H05pCZuXA+hGX80JRhAPWmA/ctRi0PQeA1yr21HAKpeH86d1dIEc3txkigQrjaC7Ng0q8C32aqNExkyguQGqu5Tf4fltr2pjJnPCrGwUHnQEanE1V9Bs7gIkmYFjcKR7c/vlPHzsuxjJnkQ1QjssuCEzLc/7y0yfMDwGoCeIS53LMA8PPNa1OySqh+CT4vfZmPb8Kgipm9xh8Q1NSPN/Px9eTytZFnzeip9lghmm8kAXh0hQSBousDCx5CDtOeJ1tMR2P3fvwOHxk6Ri8Ll4S5DVEpF4VNTEnVshT0SSp6c/f2y2+LnYSYs95C0/XcOa95SOYamIA1pvkRp6EMqUbDLyy31xZyiEvkHlJfG7QrhA2iMAAXgyBGA+Z7jsDPnwekVFSsksZLfiTpeDc2RlmrbcXeHgsiOpUhBDeA2YDkA1KNi0w3EPNyozLkVZbXyfWBrljCbbQEjqcMbt3NtboOQTYu8bU4e8sqBxgBp1OFX+NXNM7417db2gYkmaBV2Y0/7Z4icZA8Ztp0IZTOLnw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
