travis:
  secure:
    BINSTAR_TOKEN: YQeqwiVElsrgBzsWYgRJC1Bnxlh48/DMnEW7CctavwlUfp2dSl+Zvbj1lbagECT6CsxU6UswC2hOH3nRUFxQeDfnnbkYYzAIrZ33FyX6GMRmx77ZlEM00dbVdL4+uuw9U/+MjtmGG1CxjOO6rDiP6YxwjrExGRoHebKb6UI/srG3IPbBaS1AhXC/TUDAxqFCYrkko/t3hazetpP/g5ffQwPyOHvk9AuPZHgQvGxpUiSGkbb2uKfJWjvl1d8IQ/BIAqUF+oDRHqxB6JYRRudTrxFfde/7xZFFow0cYH4GEZNRBK3BGSsmqSNM4IBgCcvz09i1JxYBVzFryKgZil78efPbvzvpAeC1Gs9PmFhIyJ/CUTtSQkDv8DzZprG6bqOw4DgXrO/TrZtK8gGA62kp5p7EEohBuOT8iIIsSrYMZ/dDvQFUKSHlccQFD4NSkM+SI0ryVluVgSxuQxQED2ZOgewwsZwqSf8w2p8mg1it84g7pbYGSKu3W/usSOoMsZ0Nm9zpr3EKXHNdgv9bzf7j10v3WB86I9iC/ZkYBdqmjVLHhhinvy6gKqIMwPvnFGbwwVUgYNRq6noFnKnDSKLPouLqYHl9AmV9Q5+ga/r5Y2tIBhX8phBMArunliNAI38rGoIRJKDBth2q1DvzoV9GFI/2z+AwklnrMTt5DbVwamg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
